//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string NombreSistema { get; set; }
        public int FormularioId { get; set; }
        public int FormularioId1 { get; set; }
    
        public virtual Formulario Formulario { get; set; }
    }
}
